Repository FRONTENDBOOTCAMP-13th/JS-14-mafiaInTheMorning, pull requests merged in 2025-05, with the labels that each got.

#3 ✨ feat: typescript 폴더 추가
  src/pages/KJS/test.html
  src/typescript/test.js
Labels: feat

#12 🧪 test: 테스트 코드 추가
  src/test-yerin.js
Labels: test

#13 🧪 test: 테스트 코드 추가
  test-khm.js
Labels: test

#11 🧪test: 테스트 코드 추가
  src/typescript/kjstest.ts
Labels: test

#17 🧪 test: 파일 추가 및 삭제
  src/pages/HYR/test.html
  src/test-yerin.js
Labels: test

#19 🔧 conf:설정파일 추가/수정
  src/pages/HYR/vote.css
  src/pages/HYR/vote.html
  src/typescript/vote.js
  src/typescript/vote.ts
Labels: test

#25 ✨feat: vote 기능 수정, modal 추가
  src/main.ts
  src/pages/HYR/modal.html
  src/pages/HYR/vote.html
  src/typescript/modal.js
  src/typescript/modal.ts
  src/typescript/vote.js
  src/typescript/vote.ts
Labels: feat

#35 💄 style: 채팅방 목록 리스트 페이지 UI
  src/assets/search.png
  src/assets/search.svg
  src/pages/chatlist-page.html
  src/pages/server-page.html
  src/pages/server.html
Labels: feat

#37 💄 style: 게임 종료 결과 페이지 UI
  src/assets/citizen.svg
  src/assets/podol2.svg
  src/pages/result-page.html
Labels: feat

#41 ✨ feat: 마피아 기능 보완 및 경찰 기능 개발
  src/js/SkilsTestState.ts
  src/js/jobSkils.ts
  src/js/mafiaSkils.ts
  src/pages/JobskilsTest.html
Labels: feat

#46 ✨ feat: chatting-page 추가
  src/pages/chatlist-page.html
  src/pages/chatting-page.html
  src/pages/chatting-page.ts
Labels: feat

#48 ♻️ refactor : 모달창 , 입장 버튼 수정
  src/pages/chatlist-page.html
Labels: refactor

#50 ♻️ refactor: 페이지 연결 및 경고 수정
  src/js/start-button-modal.ts
  src/pages/chatlist-page.html
  src/pages/server-page.html
  src/pages/start-page.html
Labels: refactor

#65 💄 feat: 방생성 모달창 수정, 경로변경
  src/js/server-page/server-page.ts
  src/pages/chatlist-page.html
Labels: refactor

#67 💄 style: 메인페이지 수정, 투표창 추가
  src/js/modal.js
  src/js/modal.ts
  src/js/vote.js
  src/js/vote.ts
  src/pages/chat.html
  src/pages/chatting-page.ts
  src/pages/vote.html
Labels: feat

#74 🐛 fix: chat 코드 수정
  src/js/chat/chat.ts
Labels: bug

#78 ✨ feat: vote
  src/js/chat/vote.ts
  src/js/lib/yongchat.ts
  src/pages/chat.html
Labels: feat

#81 ♻️ refactor: 밤 시작 설정, 타이머 초기화
  src/js/chat/chat.ts
  src/js/chat/start.ts
  src/js/lib/yongchat.ts
  src/js/time.ts
  src/pages/chat.html
Labels: refactor

#83 🚧 vote: add
  src/js/chat/vote.ts
  src/js/lib/yongchat.ts
Labels: feat

#84 feat/js mafia skils
  src/js/chat/chat.ts
  src/js/chat/kill.ts
  src/js/lib/yongchat.ts
Labels: feat

#102 ✨ feat: 자동 스크롤 기능 추가 / 시간대 알림
  src/js/chat/chat.ts
  src/js/chat/chatting.ts
  src/js/time.ts
Labels: refactor

#109 ♻️ refactor: 낮, 밤 클릭이벤트 기능 수정
  src/js/chat/chat.ts
  src/js/chat/kill.ts
  src/js/chat/police.ts
  src/js/time.ts
Labels: refactor

#110 Hm/refactor all page
  index.html
  src/pages/chatlist-page.html
  src/pages/server-page.html
Labels: refactor

#112 ✨ feat : 직업 프로필 표시, 사망자 이미지 표시
  src/js/chat/chat.ts
Labels: feat

#117 Du/modify time.ts
  src/js/chat/chat.ts
  src/js/chat/chatting.ts
  src/js/lib/yongchat.ts
  src/js/time.ts
Labels: feat

#119 ✨feat: 죽은 사람은 찬반투표 불가능하게 만드는 기능
  src/js/chat/chat.ts
  src/js/lib/yongchat.ts
  src/js/room/createRoom.ts
Labels: feat

#120 ♻️ refactor: 두번째 밤에도 마피아가 킬 가능하게 수정
  src/js/time.ts
Labels: feat

#124 ✨ feat: 투표시 해당 투표한 유저 값 알 수 있도록하는 기능
  src/js/chat/chat.ts
  src/js/time.ts
Labels: feat

#126 ♻️ refactor: 투표 수 표시 수정
  src/js/chat/vote.ts
  src/js/time.ts
  src/js/vote.ts
Labels: feat

#129 🐛 fix: 배포 오류 수정
  src/js/chat/vote.ts
Labels: bug

#137 🐛 fix: 프로필 이미지 배포 문제
  src/js/chat/chat.ts
Labels: bug

#141 ✨ feat: 게임 승리 조건 개발
  src/js/chat/victory.ts
  src/js/time.ts
Labels: feat

#142 ✨ feat: 경찰 기능 추가
  src/js/chat/chat.ts
  src/js/chat/police.ts
  src/js/time.ts
Labels: feat

#149 🐛 fix: 배포 오류 이미지 경로 수정
  src/assets/player6.png
  src/assets/player7.png
  src/assets/player8.png
  src/assets/player9.png
  src/js/chat/chat.ts
Labels: bug

#150 ♻️ refactor: vote.ts 중복 파일 삭제 및 수정
  src/js/chat/vote.ts
  src/js/time.ts
  src/js/vote.ts
Labels: refactor

#156 ♻️ refactor: 배포를 위한 코드 수정
  src/js/chat/chat.ts
  src/js/chat/kill.ts
  src/js/chat/vote.ts
  src/js/time.ts
  src/main.ts
Labels: refactor

#158 🐛 bug: 프로필 이미지 경로 수정
  public/citizen.svg
  public/doctor.svg
  public/mafia.svg
  public/player9.png
  public/police.svg
  public/vote.svg
  src/js/chat/chat.ts
Labels: bug

#163 🐛 bug: 타임 버그수정
  src/js/chat/chat.ts
  src/js/chat/chatting.ts
  src/js/time.ts
Labels: bug
